### PR TITLE
Add feature

### PR DESCRIPTION
**Pull request by FevenSeyfu**
Milestones:

- [ ] Add new tasks
- [ ] Edit tasks description
- [ ] Mark a task as complete
- [ ] clear all completed tasks feature

### CODE REVIEW

**Comment by chelobotix** [comment]
## Hi @FevenSeyfu, 

Your project looks great!  

[Image](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)

- [ ] Please consider using one class for all your CRUD methods next time.
- [ ] Please consider that it is not necessary to import the Remove module twice in index.js and interactivity.js.


## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 



Cheers and Happy coding!👏👏👏

**Review by chelobotix — CHANGES_REQUESTED** [review]
Please consider fixing the observations above

**Comment by FevenSeyfu** [comment]
@chelobotix Thank you for your feedback, I have made the requested changes, kindly review.

**Review by chelobotix — APPROVED** [review]
@FevenSeyfu, your project is complete! :smile: :smile: :smile:
There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## To Highlight
- All linters are passing ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️

**Pull request merged**
